# 开发环境配置
spring:
  # 数据源配置
  datasource:
    db1: # 数据源1
      url: jdbc:mysql://localhost:3306/gs?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update #自动更新
    show-sql: true  #日志中显示sql语句